on:
  push:
    branches:
      - main
permissions: {}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - name: Run tests
      run: deno task --recursive test